# Generated by Django 5.1.1 on 2024-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
